PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://contoh.org/ontology#>

SELECT ?id ?urutan ?aksara ?transliterasi ?terjemahan
WHERE {
  ?baris a :BarisNaskah ;
         dcterms:identifier ?id ;
         :urutan ?urutan ;
         :mengandungAksara [ rdf:value ?aksara ] ;
         :hasTransliteration [ rdf:value ?transliterasi ] ;
         :hasTranslation [ rdf:value ?terjemahan ] .
}
ORDER BY ASC(?urutan)
